### ISSUE TITLE
VS2022 Preview报错

### ISSUE THREAD

**Issue by wuwao1** [fawdlstty/NetToolbox#2]
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.3.0 Preview 2.0

![屏幕截图 2022-07-24 150402](https://user-images.githubusercontent.com/29857592/180637377-c7b0384a-a210-42c3-b08a-00e07755cd8d.jpg)

fmt::format需要改成std::vformat , 还有注释掉一些其他东西

**Comment by fawdlstty** [comment]
贴贴
